name: Run Python unit tests
on:
- pull_request

env:
  AZURE_STORAGE_URL: https://atmcodeqldata.blob.core.windows.net

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions/checkout@v2

    - name: Check out CodeQL standard library
      uses: actions/checkout@v2
      with:
        repository: github/codeql
        path: codeql-lib
        ref: lgtm.com

    - name: Download CodeQL
      uses: dsaltares/fetch-gh-release-asset@939be9e72e81fe7009b6112bc96abde38bf7b68f
      with:
        repo: "github/codeql-cli-binaries"
        version: "latest"
        file: "codeql-linux64.zip"
        target: "codeql.zip"

    - name: Set up CodeQL
      run: |
        unzip -q codeql.zip
        echo "$(readlink -f codeql)" >>$GITHUB_PATH
        mkdir $HOME/.config/codeql
        echo '--ram 6000' >$HOME/.config/codeql/config
        echo '--threads 2' >>$HOME/.config/codeql/config
        echo '--timeout 900' >>$HOME/.config/codeql/config

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('code/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt-get install coinor-cbc
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv env
        source env/bin/activate
        pip install -r code/requirements.txt
        python -m pip install -i https://pypi.gurobi.com gurobipy

    - name: Run unit tests
      env:
          # Some tests need to pull data from Azure blob storage
          ATM_BLOB_STORE_SAS_TOKEN: ${{ secrets.ATM_BLOB_STORE_SAS_TOKEN }}
      run: |
        source env/bin/activate
        cd /home/runner/work/ml-ql-taint-specification-mining/ml-ql-taint-specification-mining
        pytest --full-trace -v -s
