name: Run python unit tests
on:
- pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt-get install coinor-cbc
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        source env/bin/activate
        pytest --full-trace -v
